version: "3.8"
services:
  frontend:
    build: 
      context: ./frontend
      network: host
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      network: host
    volumes:
      - ./backend/PSE.sqlite3:/backend/PSE.sqlite3'
    ports:
      - "8000:8000"

volumes:
  PSE.sqlite3:
