version: "3.8"
services:
  frontend:
    build: ./frontend
    links:
      - "backend"
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./backend
    links:
      - "frontend"
    volumes:
      - ./backend/PSE.sqlite3:/backend/PSE.sqlite3'
    ports:
      - "8000:8000"

volumes:
  PSE.sqlite3:
