# Generated by Django 5.0.2 on 2024-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_emergency_medication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicine',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
