# Generated by Django 5.0.2 on 2024-03-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_emergency_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='stock',
            field=models.CharField(default='no', max_length=10),
            preserve_default=False,
        ),
    ]
