# Generated by Django 5.0.2 on 2024-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_medication_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='stock',
            field=models.CharField(max_length=100),
        ),
    ]
