# Generated by Django 5.0.2 on 2024-03-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_medication_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='stock',
        ),
    ]
